
var api=null,timer=null,lang='nl',lastData=null;
function tr(nl,en,de,fr,es){var l=(lang||'nl').slice(0,2);return ({nl:nl,en:en,de:de,fr:fr,es:es}[l])||en||nl}
function fmt(n,u,d){var n2=Number(n||0);return n2.toLocaleString(undefined,{maximumFractionDigits:d==null?2:d})+' '+u}
function dt(v){if(!v)return '-';try{return new Date(v).toLocaleString()}catch(e){return String(v)}}
function dur(ms){ms=Number(ms||0);if(ms<1000)return '0s';var s=Math.floor(ms/1000),h=Math.floor(s/3600),m=Math.floor((s%3600)/60);s=s%60;return (h?h+'u ':'')+(m?m+'m ':'')+(!h?s+'s':'')}
function liveDuration(a){if(a.status==='active'&&a.startTime){return Date.now()-new Date(a.startTime).getTime()}return a.durationMs||0}
function hasUsage(v){return Number(v||0)>0}
function meter(label,value,unit){return '<div class="meter"><span>'+label+'</span><strong>'+value+' '+unit+'</strong></div>'}
function usageMeters(values){var html='';if(hasUsage(values.water))html+=meter('Water',fmt(values.water,'L',2),'');if(hasUsage(values.energy))html+=meter('kWh',fmt(values.energy,'',3),'');if(hasUsage(values.gas))html+=meter('Gas',fmt(values.gas,'m³',3),'');return html?'<div class="meters">'+html+'</div>':''}
function usageSummary(values){var parts=[];if(hasUsage(values.water))parts.push('Water: '+fmt(values.water,'L',2));if(hasUsage(values.energy))parts.push('kWh: '+fmt(values.energy,'',3));if(hasUsage(values.gas))parts.push('Gas: '+fmt(values.gas,'m³',3));return parts.join(' · ')}
function render(data){lastData=data||{};lang=(data&&data.language)||lang;var list=document.getElementById('list');var acts=Array.isArray(data.activities)?data.activities:[];var active=acts.filter(function(a){return a.status==='active'}).length;document.getElementById('summary').textContent=acts.length?active+' '+tr('actief','active','aktiv','active','activas')+' · '+acts.length+' '+tr('ingesteld','configured','eingerichtet','configurées','configuradas'):tr('Geen activiteiten ingesteld','No activities configured','Keine Aktivitäten eingerichtet','Aucune activité configurée','No hay actividades configuradas');list.innerHTML='';if(!acts.length){list.innerHTML='<div class="empty">'+tr('Maak activiteiten aan via de instellingenpagina.','Create activities from the settings page.','Erstelle Aktivitäten über die Einstellungsseite.','Crée des activités depuis la page de réglages.','Crea actividades desde la página de ajustes.')+'</div>';return}acts.forEach(function(a){var last=a.lastSession||{};var ms=liveDuration(a);var row=document.createElement('div');row.className='activity';row.innerHTML='<div class="row"><div><div class="name">'+(a.name||tr('Activiteit','Activity','Aktivität','Activité','Actividad'))+'</div><div class="meta">'+(a.status==='active'?tr('Gestart','Started','Gestartet','Démarrée','Iniciada')+': '+dt(a.startTime)+' · '+dur(ms):tr('Laatste sessie','Last session','Letzte Sitzung','Dernière session','Última sesión')+': '+(last.endTime?dt(last.endTime):'-'))+'<br>'+tr('Voorwaarden','Conditions','Bedingungen','Conditions','Condiciones')+': '+(a.trueConditions||0)+'/'+(a.requiredConditions||1)+'</div></div><div class="badge '+(a.status==='active'?'active':'')+'">'+(a.status==='active'?tr('Actief','Active','Aktiv','Active','Activa'):tr('Stand-by','Standby','Standby','Veille','Espera'))+'</div></div>'+usageMeters({water:a.waterUsed||last.waterUsed||0,energy:a.energyKwh||last.energyKwh||0,gas:a.gasUsed||last.gasUsed||0});row.addEventListener('click',function(){showDetail(a)});list.appendChild(row)})}

function enableDetailScroll(){var b=document.getElementById('detailBody');if(!b||b.dataset.scrollFix==='1')return;b.dataset.scrollFix='1';var lastY=0;b.addEventListener('wheel',function(e){if(b.scrollHeight<=b.clientHeight)return;e.preventDefault();e.stopPropagation();b.scrollTop+=e.deltaY;},{passive:false});b.addEventListener('touchstart',function(e){if(e.touches&&e.touches.length)lastY=e.touches[0].clientY;},{passive:true});b.addEventListener('touchmove',function(e){if(!e.touches||!e.touches.length||b.scrollHeight<=b.clientHeight)return;var y=e.touches[0].clientY;var dy=lastY-y;lastY=y;e.preventDefault();e.stopPropagation();b.scrollTop+=dy;},{passive:false});}
function showDetail(a){var h=Array.isArray(a.history)?a.history:[];document.getElementById('detailTitle').textContent=a.name||tr('Activiteit','Activity','Aktivität','Activité','Actividad');var html='<div class="section"><strong>'+tr('Status','Status','Status','Statut','Estado')+':</strong> '+(a.status==='active'?tr('Actief','Active','Aktiv','Active','Activa'):tr('Stand-by','Standby','Standby','Veille','Espera'))+'<br><strong>'+tr('Starttijd','Start time','Startzeit','Heure de début','Hora de inicio')+':</strong> '+dt(a.startTime)+'<br><strong>'+tr('Eindtijd','End time','Endzeit','Heure de fin','Hora de fin')+':</strong> '+dt(a.endTime)+'<br><strong>'+tr('Duur','Duration','Dauer','Durée','Duración')+':</strong> '+dur(liveDuration(a))+'</div>'+usageMeters({water:a.waterUsed||0,energy:a.energyKwh||0,gas:a.gasUsed||0})+'<div class="section"><strong>'+tr('Geschiedenis','History','Verlauf','Historique','Historial')+'</strong>';
if(!h.length)html+='<div class="session">'+tr('Nog geen eerdere sessies.','No previous sessions yet.','Noch keine früheren Sitzungen.','Aucune session précédente.','Aún no hay sesiones anteriores.')+'</div>';h.forEach(function(s){html+='<div class="session"><strong>'+dt(s.startTime)+' - '+dt(s.endTime)+'</strong><br>'+tr('Duur','Duration','Dauer','Durée','Duración')+': '+dur(s.durationMs)+(usageSummary({water:s.waterUsed,energy:s.energyKwh,gas:s.gasUsed})?' · '+usageSummary({water:s.waterUsed,energy:s.energyKwh,gas:s.gasUsed}):'')+'</div>'});html+='</div>';document.getElementById('detailBody').innerHTML=html;enableDetailScroll();document.body.classList.add('modal-open');document.getElementById('detail').style.display='flex';setTimeout(function(){var b=document.getElementById('detailBody');if(b){b.scrollTop=0;b.focus&&b.focus()}},0)}
function load(){if(!api)return;api('GET','/',{}).then(render).catch(function(e){document.getElementById('list').innerHTML='<div class="error">'+(e&&e.message?e.message:tr('Kan activiteiten niet laden.','Could not load activities.','Aktivitäten konnten nicht geladen werden.','Impossible de charger les activités.','No se pudieron cargar las actividades.'))+'</div>'})}
function onHomeyReady(Homey){window.Homey=Homey;try{lang=(Homey.__ && Homey.__('settings.title'))?Homey.i18n.getLanguage():(Homey.manifest&&Homey.manifest.language)||'nl'}catch(e){}api=Homey.api.bind(Homey);document.querySelector('[data-i18n="title"]').textContent=tr('Activiteiten','Activities','Aktivitäten','Activités','Actividades');document.getElementById('refresh').addEventListener('click',load);document.getElementById('close').addEventListener('click',function(){document.getElementById('detail').style.display='none';document.body.classList.remove('modal-open')});document.getElementById('detail').addEventListener('click',function(e){if(e.target===this){this.style.display='none';document.body.classList.remove('modal-open')}});Homey.ready({height:420});load();timer=setInterval(load,5000)}
document.addEventListener('DOMContentLoaded',function(){document.querySelector('[data-i18n="title"]').textContent=tr('Activiteiten','Activities','Aktivitäten','Activités','Actividades')});
